terraform init
terraform import akamai_gtm_domain.cdn03_great-demo_nl "cdn03.great-demo.nl"
terraform import akamai_gtm_datacenter.Clone__5__of_NY "cdn03.great-demo.nl:5"
terraform import akamai_gtm_datacenter.Clone__4__of_NY "cdn03.great-demo.nl:4"
terraform import akamai_gtm_datacenter.NY "cdn03.great-demo.nl:2"
terraform import akamai_gtm_datacenter.RTM "cdn03.great-demo.nl:1"
terraform import akamai_gtm_datacenter.Clone__3__of_Default_Datacenter "cdn03.great-demo.nl:3"
terraform import akamai_gtm_property.pool3 "cdn03.great-demo.nl:pool3"
terraform import akamai_gtm_property.demo-pool "cdn03.great-demo.nl:demo-pool"
terraform import akamai_gtm_property.pool1 "cdn03.great-demo.nl:pool1"
terraform import akamai_gtm_property.pool-ipv6 "cdn03.great-demo.nl:pool-ipv6"
terraform import akamai_gtm_property.pool "cdn03.great-demo.nl:pool"
terraform import akamai_gtm_property.pool-ipv4 "cdn03.great-demo.nl:pool-ipv4"
terraform import akamai_gtm_property._ "cdn03.great-demo.nl:*"
terraform import akamai_gtm_property.pool2 "cdn03.great-demo.nl:pool2"
terraform import akamai_gtm_property._ "cdn03.great-demo.nl:@"
terraform import akamai_gtm_geomap.GEO_map_for_wildcard "cdn03.great-demo.nl:GEO map for wildcard"